baseURL = 'https://yayoyuyu.github.io/'
languageCode = 'ja'
title = 'ﾌｺﾞｺﾞｺﾞｺﾞ'
theme = 'PaperMod'

[params.homeInfoParams]
Title = 'ふごご'
Content = 'がんばります'

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/yayoyuyu'
