baseURL = 'https://yayoyuyu.github.io/'
languageCode = 'ja'
title = 'ﾌｺﾞｺﾞｺﾞｺﾞ'
theme = 'stack'

[params.sidebar]
subtitle = 'がんばります'

[params.sidebar.avatar]
src = 'https://avatars.githubusercontent.com/u/112897090'
local = false

[[menu.social]]
identifier = 'github'
name = 'GitHub'
url = 'https://github.com/yayoyuyu'

[menu.social.params]
icon = 'brand-github'
